FROM python:3.9

WORKDIR /api

COPY pyproject.toml poetry.lock /api/

RUN pip install poetry && \
    poetry config virtualenvs.create false && \
    poetry install --no-dev --no-interaction --no-ansi

COPY . .

EXPOSE 5002

ENV FLASK_APP=earth_locations.py
ENV FLASK_RUN_HOST='0.0.0.0'

CMD ["poetry", "run", "flask", "run", "--host=0.0.0.0"]